#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jan  3 17:58:42 2022

@author: avanthikasenthil
"""

import re

from bs4 import BeautifulSoup as bs
import urllib.request
import requests
import pandas as pd
from pandas import DataFrame as df
import json
import time
from selenium import webdriver
import numpy as np
import pandas as pd

PATH = "/Users/avanthikasenthil/Downloads/chromedriver 6"
#driver = webdriver.Chrome(PATH)


url_real = "https://www.pnd.ie/forums/0"
page_url = "https://www.pnd.ie/forums/0?page=2"

links = []
content = np.array(["Post ID", "Header","Name & Date", "Comment"])
comments = np.array(["Comment ID", "Post ID", "Name & Date", "Post"])
source = urllib.request.urlopen(url_real)
soup = bs(source, 'lxml')

for i in range(1, 17):
    if i ==1:
        source = urllib.request.urlopen(url_real)
        soup = bs(source, 'lxml')
    else:
        url = url_real + "?page=" + str(i)
        source = urllib.request.urlopen(url)
        soup = bs(source, 'lxml')
    
    for link in soup.findAll("h3", class_="panel-title", recursive = True):
        linkz = link.find("a")
        links.append("https://www.pnd.ie" + linkz.get("href"))
    
count = 0
commentID = 0

for i in range(0, len(links)):
    source = urllib.request.urlopen(links[i])
    soup = bs(source, 'lxml')
    
    heading = soup.find("h1", class_="heading-title pull-left").text
    commentCount = -1
    for comment in soup.findAll("div", class_="individual-post well"):
        
        header = comment.find("div", class_="col-md-10")
        name_date = comment.find("h4").text
        body = header.find("p").text
        if commentCount == -1:
              contentRow =[count, heading,name_date, body]
              content = np.vstack([content, contentRow])
        else:
            comRow = [commentID, count, name_date, body ]
            comments = np.vstack([comments, comRow])
        
        commentID += 1
        commentCount += 1
        
    
    count += 1

df = pd.DataFrame(content)
df.to_csv('content_ireland.csv')

df = pd.DataFrame(comments)
df.to_csv('comments_ireland.csv')

                
        
